<?php

declare(strict_types=1);

namespace PhpCodeArch\Application\Service;

use PhpCodeArch\Application\CliFormatter;
use PhpCodeArch\Application\CliOutput;
use PhpCodeArch\Application\Config;
use PhpCodeArch\Metrics\MetricKey;
use PhpCodeArch\Metrics\Model\MetricValue;
use PhpCodeArch\Metrics\Model\PackageMetrics\PackageMetricsCollection;
use PhpCodeArch\Predictions\PredictionInterface;
use PhpCodeArch\Predictions\Problems\ProblemInterface;
use PhpCodeArch\Report\DataProvider\DataProviderFactory;

class ClaudeMdGenerator
{
    public function generate(Config $config, DataProviderFactory $dataProviderFactory, CliOutput $output): void
    {
        $output->outWithMemory('Generating CLAUDE.md...');

        $projectData = $dataProviderFactory->getProjectDataProvider()->getTemplateData();
        $problemData = $dataProviderFactory->getProblemDataProvider()->getTemplateData();
        $gitData = $dataProviderFactory->getGitDataProvider()->getTemplateData();

        $elementsRaw = $projectData['elements'] ?? null;
        $metrics = is_array($elementsRaw) ? $elementsRaw : [];
        $lines = [];

        $lines[] = '# Project Architecture (auto-generated by PhpCodeArcheology)';
        $lines[] = '';
        $lines[] = '## Overview';
        $lines[] = '';

        $overviewMetrics = [
            MetricKey::OVERALL_FILES => 'Files',
            MetricKey::OVERALL_CLASSES => 'Classes',
            MetricKey::OVERALL_FUNCTION_COUNT => 'Functions',
            MetricKey::OVERALL_METHODS_COUNT => 'Methods',
            MetricKey::OVERALL_LOC => 'Lines of Code',
            MetricKey::OVERALL_LLOC => 'Logical Lines of Code',
        ];

        foreach ($overviewMetrics as $key => $label) {
            if (isset($metrics[$key]) && $metrics[$key] instanceof MetricValue) {
                $formatted = $metrics[$key]->getValueFormatted();
                $lines[] = '- '.$label.': '.(is_scalar($formatted) ? (string) $formatted : '');
            }
        }

        $lines[] = '';
        $lines[] = '## Code Quality';
        $lines[] = '';

        $qualityMetrics = [
            MetricKey::OVERALL_AVG_CC => 'Avg Cyclomatic Complexity',
            MetricKey::OVERALL_AVG_MI => 'Avg Maintainability Index',
            MetricKey::HEALTH_SCORE => 'Health Score',
            MetricKey::OVERALL_TECHNICAL_DEBT_SCORE => 'Technical Debt Score',
        ];

        foreach ($qualityMetrics as $key => $label) {
            if (isset($metrics[$key]) && $metrics[$key] instanceof MetricValue) {
                $formatted = $metrics[$key]->getValueFormatted();
                $lines[] = '- '.$label.': '.(is_scalar($formatted) ? (string) $formatted : '');
            }
        }

        $lines[] = '';
        $lines[] = '## Package Structure';
        $lines[] = '';

        $packagesData = $dataProviderFactory->getPackageDataProvider()->getTemplateData();
        $packagesRaw = $packagesData['packages'] ?? null;
        $packages = is_array($packagesRaw) ? $packagesRaw : [];
        if (!empty($packages)) {
            foreach (array_slice($packages, 0, 20, true) as $packageKey => $package) {
                $name = ($package instanceof PackageMetricsCollection) ? $package->getName() : (string) $packageKey;
                $lines[] = '- `'.$name.'`';
            }
        } else {
            $lines[] = 'No package data available.';
        }

        $lines[] = '';
        $lines[] = '## Top Problems';
        $lines[] = '';

        $allProblems = [];
        foreach (['fileProblems', 'classProblems', 'functionProblems'] as $categoryKey) {
            $categoryRaw = $problemData[$categoryKey] ?? null;
            if (!is_array($categoryRaw)) {
                continue;
            }
            foreach ($categoryRaw as $entityId => $entityProblems) {
                if (!is_array($entityProblems)) {
                    continue;
                }
                $data = $entityProblems['data'] ?? null;
                $nameRaw = (is_object($data) && method_exists($data, 'getName')) ? $data->getName() : null;
                $name = is_string($nameRaw) ? $nameRaw : (string) $entityId;

                $problemsList = $entityProblems['problems'] ?? null;
                if (!is_array($problemsList)) {
                    continue;
                }
                foreach ($problemsList as $problem) {
                    if (!$problem instanceof ProblemInterface) {
                        continue;
                    }
                    $allProblems[] = [
                        'level' => $problem->getProblemLevel(),
                        'entity' => $name,
                        'message' => $problem->getMessage(),
                        'recommendation' => $problem->getRecommendation(),
                    ];
                }
            }
        }

        usort($allProblems, fn (array $a, array $b): int => $b['level'] <=> $a['level']);

        foreach (array_slice($allProblems, 0, 15) as $problem) {
            $levelStr = match ($problem['level']) {
                PredictionInterface::ERROR => 'ERROR',
                PredictionInterface::WARNING => 'WARNING',
                default => 'INFO',
            };
            $lines[] = '- ['.$levelStr.'] '.$problem['entity'].': '.$problem['message'];
            if ('' !== $problem['recommendation']) {
                $lines[] = '  - Recommendation: '.$problem['recommendation'];
            }
        }

        $lines[] = '';
        $lines[] = '## Recommendations';
        $lines[] = '';

        $errorMetric = $metrics[MetricKey::OVERALL_ERROR_COUNT] ?? null;
        $errorCount = ($errorMetric instanceof MetricValue) ? $errorMetric->getValue() : 0;
        $errorCount = is_numeric($errorCount) ? (int) $errorCount : 0;

        $warningMetric = $metrics[MetricKey::OVERALL_WARNING_COUNT] ?? null;
        $warningCount = ($warningMetric instanceof MetricValue) ? $warningMetric->getValue() : 0;
        $warningCount = is_numeric($warningCount) ? (int) $warningCount : 0;

        if ($errorCount > 0) {
            $lines[] = '- Fix '.$errorCount.' errors as highest priority';
        }
        if ($warningCount > 0) {
            $lines[] = '- Address '.$warningCount.' warnings to improve code quality';
        }

        $hotspotsRaw = $gitData['hotspots'] ?? null;
        $hotspots = is_array($hotspotsRaw) ? array_slice($hotspotsRaw, 0, 5) : [];
        if ([] !== $hotspots) {
            $lines[] = '- Refactor these hotspots (high churn + complexity):';
            foreach ($hotspots as $hotspot) {
                if (!is_array($hotspot)) {
                    continue;
                }
                $hotspotName = is_scalar($hotspot['name'] ?? null) ? (string) $hotspot['name'] : '';
                $hotspotChurn = is_numeric($hotspot['churn'] ?? null) ? (int) $hotspot['churn'] : 0;
                $hotspotCc = is_numeric($hotspot['cc'] ?? null) ? (int) $hotspot['cc'] : 0;
                $lines[] = '  - `'.$hotspotName.'` (churn:'.$hotspotChurn.' cc:'.$hotspotCc.')';
            }
        }

        $lines[] = '';

        $runningDirRaw = $config->get('runningDir');
        $runningDir = is_string($runningDirRaw) ? $runningDirRaw : (string) getcwd();
        $claudeMdPath = $runningDir.DIRECTORY_SEPARATOR.'CLAUDE.md';
        file_put_contents($claudeMdPath, implode("\n", $lines));

        $formatter = $output->getFormatter() ?? new CliFormatter();
        $output->outNl($formatter->success('CLAUDE.md generated at '.$claudeMdPath));
    }
}
