<?php

declare(strict_types=1);

namespace PhpCodeArch\Application\Service;

use PhpCodeArch\Application\CliFormatter;
use PhpCodeArch\Application\CliOutput;
use PhpCodeArch\Application\Config;
use PhpCodeArch\Predictions\PredictionInterface;
use PhpCodeArch\Report\DataProvider\DataProviderFactory;

class ClaudeMdGenerator
{
    public function generate(Config $config, DataProviderFactory $dataProviderFactory, CliOutput $output): void
    {
        $output->outWithMemory('Generating CLAUDE.md...');

        $projectData = $dataProviderFactory->getProjectDataProvider()->getTemplateData();
        $problemData = $dataProviderFactory->getProblemDataProvider()->getTemplateData();
        $gitData = $dataProviderFactory->getGitDataProvider()->getTemplateData();

        $metrics = $projectData['elements'] ?? [];
        $lines = [];

        $lines[] = '# Project Architecture (auto-generated by PhpCodeArcheology)';
        $lines[] = '';
        $lines[] = '## Overview';
        $lines[] = '';

        $overviewMetrics = [
            'overallFiles' => 'Files',
            'overallClasses' => 'Classes',
            'overallFunctionCount' => 'Functions',
            'overallMethodsCount' => 'Methods',
            'overallLoc' => 'Lines of Code',
            'overallLloc' => 'Logical Lines of Code',
        ];

        foreach ($overviewMetrics as $key => $label) {
            if (isset($metrics[$key]) && $metrics[$key] instanceof \PhpCodeArch\Metrics\Model\MetricValue) {
                $lines[] = '- ' . $label . ': ' . $metrics[$key]->getValueFormatted();
            }
        }

        $lines[] = '';
        $lines[] = '## Code Quality';
        $lines[] = '';

        $qualityMetrics = [
            'overallAvgCC' => 'Avg Cyclomatic Complexity',
            'overallAvgMI' => 'Avg Maintainability Index',
            'healthScore' => 'Health Score',
            'overallTechnicalDebtScore' => 'Technical Debt Score',
        ];

        foreach ($qualityMetrics as $key => $label) {
            if (isset($metrics[$key]) && $metrics[$key] instanceof \PhpCodeArch\Metrics\Model\MetricValue) {
                $lines[] = '- ' . $label . ': ' . $metrics[$key]->getValueFormatted();
            }
        }

        $lines[] = '';
        $lines[] = '## Package Structure';
        $lines[] = '';

        $packagesData = $dataProviderFactory->getPackagDataProvider()->getTemplateData();
        $packages = $packagesData['packages'] ?? [];
        if (!empty($packages)) {
            foreach (array_slice($packages, 0, 20, true) as $packageKey => $package) {
                $name = method_exists($package, 'getName') ? $package->getName() : $packageKey;
                $lines[] = '- `' . $name . '`';
            }
        } else {
            $lines[] = 'No package data available.';
        }

        $lines[] = '';
        $lines[] = '## Top Problems';
        $lines[] = '';

        $allProblems = [];
        foreach (['fileProblems', 'classProblems', 'functionProblems'] as $key) {
            foreach ($problemData[$key] ?? [] as $entityId => $entityProblems) {
                $data = $entityProblems['data'] ?? null;
                $name = ($data !== null && method_exists($data, 'getName')) ? $data->getName() : $entityId;

                foreach ($entityProblems['problems'] ?? [] as $problem) {
                    $allProblems[] = [
                        'level' => $problem->getProblemLevel(),
                        'entity' => $name,
                        'message' => $problem->getMessage(),
                        'recommendation' => $problem->getRecommendation(),
                    ];
                }
            }
        }

        usort($allProblems, fn($a, $b) => $b['level'] <=> $a['level']);

        foreach (array_slice($allProblems, 0, 15) as $problem) {
            $levelStr = match ($problem['level']) {
                PredictionInterface::ERROR => 'ERROR',
                PredictionInterface::WARNING => 'WARNING',
                default => 'INFO',
            };
            $lines[] = '- [' . $levelStr . '] ' . $problem['entity'] . ': ' . $problem['message'];
            if ($problem['recommendation'] !== '') {
                $lines[] = '  - Recommendation: ' . $problem['recommendation'];
            }
        }

        $lines[] = '';
        $lines[] = '## Recommendations';
        $lines[] = '';

        $errorCount = $metrics['overallErrorCount']?->getValue() ?? 0;
        $warningCount = $metrics['overallWarningCount']?->getValue() ?? 0;

        if ($errorCount > 0) {
            $lines[] = '- Fix ' . $errorCount . ' errors as highest priority';
        }
        if ($warningCount > 0) {
            $lines[] = '- Address ' . $warningCount . ' warnings to improve code quality';
        }

        $hotspots = array_slice($gitData['hotspots'] ?? [], 0, 5);
        if (!empty($hotspots)) {
            $lines[] = '- Refactor these hotspots (high churn + complexity):';
            foreach ($hotspots as $hotspot) {
                $lines[] = '  - `' . $hotspot['name'] . '` (churn:' . $hotspot['churn'] . ' cc:' . $hotspot['cc'] . ')';
            }
        }

        $lines[] = '';

        $claudeMdPath = ($config->get('runningDir') ?? getcwd()) . DIRECTORY_SEPARATOR . 'CLAUDE.md';
        file_put_contents($claudeMdPath, implode("\n", $lines));

        $formatter = $output->getFormatter() ?? new CliFormatter();
        $output->outNl($formatter->success('CLAUDE.md generated at ' . $claudeMdPath));
    }
}
