<?php

declare(strict_types=1);

namespace PhpCodeArch\Application\Command;

use PhpCodeArch\Application\CliFormatter;
use PhpCodeArch\Application\CliOutput;
use PhpCodeArch\Application\Config;
use Symfony\Component\Yaml\Yaml;

class InitCommand
{
    private const CONFIG_FILENAME = 'php-codearch-config.yaml';

    private const KNOWN_SOURCE_DIRS = ['src', 'app', 'lib', 'source'];

    private const VALID_REPORT_TYPES = ['html', 'markdown', 'json', 'sarif', 'ai-summary'];

    public function execute(Config $config, CliOutput $output, CliFormatter $formatter): int
    {
        $runningDir = $config->get('runningDir');
        $runningDir = is_string($runningDir) ? $runningDir : (getcwd() ?: '');
        $configPath = $runningDir.DIRECTORY_SEPARATOR.self::CONFIG_FILENAME;

        $output->outNl($formatter->bold('PhpCodeArcheology — Project Setup'));
        $output->outNl();

        // Check if config already exists
        if (file_exists($configPath)) {
            $output->outNl($formatter->warning('Config file already exists: '.self::CONFIG_FILENAME));
            $overwrite = $output->prompt('Overwrite? (y/N)', 'N');
            if ('y' !== strtolower($overwrite)) {
                $output->outNl('Aborted.');

                return 0;
            }
        }

        // Detect source directories
        $detected = $this->detectSourceDirs($runningDir);
        $defaultInclude = [] === $detected ? 'src' : implode(', ', $detected);

        $output->outNl($formatter->dim('Detected directories: '.([] !== $detected ? implode(', ', $detected) : 'none')));
        $output->outNl();

        // Interactive prompts
        $includeInput = $output->prompt('Source directories (comma-separated)', $defaultInclude);
        $include = array_map(trim(...), explode(',', $includeInput));

        $reportDir = $output->prompt('Report directory', 'tmp/report');

        $reportType = $output->prompt('Report type ('.implode('/', self::VALID_REPORT_TYPES).')', 'html');
        if (!in_array($reportType, self::VALID_REPORT_TYPES, true)) {
            $output->outNl($formatter->warning("Unknown report type '$reportType', using 'html'."));
            $reportType = 'html';
        }

        $packageSize = $output->prompt('Package size (namespace depth)', '2');

        // Build config
        $configData = [
            'include' => $include,
            'exclude' => [],
            'extensions' => ['php'],
            'packageSize' => (int) $packageSize,
            'reportDir' => $reportDir,
            'reportType' => $reportType,
            'history' => ['enable' => true],
        ];

        // Generate YAML with header comment
        $yaml = Yaml::dump($configData, 4, 2);

        $header = <<<HEADER
        ---
        ############################################
        # PhpCodeArcheology Config File
        # Generated by: phpcodearcheology init
        ############################################

        HEADER;

        $content = $header."\n".$yaml;

        // Ensure report directory exists
        $reportDirPath = $runningDir.DIRECTORY_SEPARATOR.$reportDir;
        if (!is_dir($reportDirPath)) {
            mkdir($reportDirPath, 0755, true);
        }

        file_put_contents($configPath, $content);

        $output->outNl();
        $output->outNl($formatter->success('Config written to '.self::CONFIG_FILENAME));
        $output->outNl($formatter->dim('Run phpcodearcheology to start analysis.'));
        $output->outNl();

        return 0;
    }

    /** @return string[] */
    private function detectSourceDirs(string $dir): array
    {
        $found = [];

        foreach (self::KNOWN_SOURCE_DIRS as $candidate) {
            if (is_dir($dir.DIRECTORY_SEPARATOR.$candidate)) {
                $found[] = $candidate;
            }
        }

        return $found;
    }
}
